"""add table category income personal

Revision ID: 7ddfce2b31a8
Revises: 53909ddc12f4
Create Date: 2024-09-16 01:22:12.444735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7ddfce2b31a8'
down_revision: Union[str, None] = '53909ddc12f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_income_personal',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('income_personal', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('income_personal', sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key('income_category_personal_fkey', 'income_personal', 'category_income_personal', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('income_category_personal_fkey', 'income_personal', type_='foreignkey')
    op.drop_column('income_personal', 'category_name')
    op.drop_column('income_personal', 'category_id')
    op.drop_table('category_income_personal')
    # ### end Alembic commands ###
